# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem "mdl", "0.12.0"
  gem "rubocop", "1.4.0"
  gem "rubocop-packaging", "~> 0.5", ">= 0.5.2"
  gem "rubocop-performance", "~> 1.11", ">= 1.11.0"
  gem "yard", "0.9.26"
end
