# frozen_string_literal: true

source "https://rubygems.org"

group :development do
  gem "mdl", "0.11.0"
  gem "rubocop", "1.3.1"
  gem "rubocop-packaging", "~> 0.5", ">= 0.5.1"
  gem "rubocop-performance", "~> 1.10", ">= 1.10.2"
  gem "yard", "0.9.26"
end
